# Generated by Django 3.1.2 on 2020-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Tytuł')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Podtytuł(Opcjonalnie)')),
                ('text', models.TextField(verbose_name='Treść Posta')),
                ('image', models.ImageField(upload_to='uploads/articles/thumbnails', verbose_name='Zdjęcie')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('hits', models.IntegerField(default=0, editable=False, verbose_name='Wyświetlenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
                'ordering': ['-created_at', 'updated_at'],
            },
        ),
    ]
