# Generated by Django 3.1.2 on 2020-11-03 21:07

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tagi'),
        ),
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis(Opcjonalnie')),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(upload_to='uploads/art/images', verbose_name='Zdjęcie')),
                ('visible', models.BooleanField(default=True, verbose_name='Wyświetlaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tagi')),
            ],
            options={
                'verbose_name': 'Sztuka',
                'verbose_name_plural': 'Sztuka',
                'ordering': ['-created_at', 'updated_at'],
            },
        ),
    ]
