# Generated by Django 3.1.2 on 2020-11-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subskrybent', 'verbose_name_plural': 'Subskrybenci'},
        ),
    ]
