# Generated by Django 3.1.2 on 2020-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201103_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Nazwa Kategorii/Kolekcji')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis(Opcjonalnie)')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Kategoria Produktu',
                'verbose_name_plural': 'Kategorie Produktów',
                'ordering': ('name', 'created_at'),
            },
        ),
    ]
