# Generated by Django 3.1.2 on 2020-11-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_productimage_productoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conf_num', models.CharField(max_length=15)),
                ('confirmed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subskrybent Newsletteru',
                'verbose_name_plural': 'Subskrybenci Newsletteru',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Zdjęcie produktu', 'verbose_name_plural': 'Zdjęcia produktów'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Wstrzymaj'), ('published', 'Opublikuj')], default='draft', max_length=100, verbose_name='Status publikacji'),
        ),
    ]
