# Generated by Django 3.1.2 on 2020-11-20 22:20

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201120_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '900x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniaturka 800x300'),
        ),
    ]
