# Generated by Django 3.1.2 on 2020-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201121_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='Główne zdjęcie'),
        ),
    ]
