# Generated by Django 3.1.2 on 2020-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_productimage_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptions',
            name='sold_out',
            field=models.BooleanField(default=False, verbose_name='Wyprzedane'),
        ),
    ]
