# Generated by Django 2.2.1 on 2019-12-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191102_1757'),
        ('blog', '0005_auto_20191102_1750'),
    ]

    operations = [
    ]
